#开发环境

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 200695

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6FPr6pL8qTp1WdwWcs
    access-key-secret: WmgKfxKdKYb1VVXuJAsp397oxoUhHr
    bucket-name: java-web01-light